spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  main:
    lazy-initialization: true
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ioanntrapeznikov@gmail.com
    password: password
    auth: true
    starttlsEnable: true
    protocol: smtp
