#YOU SHOULD CREATE application.yml file and  FILL PASSWORD FOR WORKING
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: root
    password: root

mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ioanntrapeznikov@gmail.com
    password: password
    auth: true
    starttlsEnable: true
    protocol: smtp
    defaultSender: ioanntrapeznikov@gmail.com
server:
  port: 8081
